### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by MuhammadUzair** [nahid/nahid.co#6]
![error](https://cloud.githubusercontent.com/assets/15572020/17136666/1ce5c8b8-5350-11e6-92ca-ed66d2663f1c.JPG)

**Comment by nahid** [comment]
its not Talk related issue. Please setup a valid key in your .env file.

**Comment by MuhammadUzair** [comment]
Thank you for your respond.
This Command solve my Issue :
php artisan key:generate
